### ISSUE TITLE
Derivative logo for python-can

### ISSUE THREAD

**Issue by hardbyte** [linux-can/can-logos#2]
Over at https://github.com/hardbyte/python-can/issues/271 we've been thinking about a project logo for a while and I wondered if it would be okay to use a derivative of your linux-can logo? Under CC I believe this is okay as long as we provide attribution?

I'm thinking something like this:

![python-can-logo-idea](https://user-images.githubusercontent.com/855189/42141174-b5100d44-7dea-11e8-954d-f4db65f12a16.png)

*Context*: [python-can](https://github.com/hardbyte/python-can) provides a high level python wrapper for socketcan (among wrapping other devices for other operating systems).

**Comment by hartkopp** [comment]
Funny idea. The license information of the Linux-Tux can be found in the meta data of the SVGs:

----8<--- snip!
Tux Logo: Larry Ewing, Simon Budig and Anja Gerwinski

Flat Tux Logo (reduced colors) by: Simon Budig
Monochrome Tux by Gjwucherpfennig http://en.wikipedia.org/wiki/File:Tux-Shirt.svg

CAN Logo: usage of the commonly known CAN logo/font thankfully ganted by Thilo Schumann, CAN in Automation www.can-cia.org

Thanks to: Andrea Schick, Lorenz Bohrer, Jens Krueger, Wolfgang Grandegger and all the others from the SocketCAN Mailing List for their feedback. And to Andre Naujoks for the Inkscape assistance :)
----8<--- snip!

So you might just add your own credits to the meta data and continue with your own work.

If you want you logo to be hosted in the Linux-CAN logo repo please let me know.

Best,
Oliver

**Comment by hardbyte** [comment]
Thanks Oliver - I'll do that.
